config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :tasks do
    resources :histories
  end
  get "calendar" => "histories#calendar"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :task
  validates :action_at, presence: { message: "日付を登録してください" }, uniqueness: { scope: :task_id, massage: "同じ日付は登録できません" }
  validate :action_at_be_in_the_future
  default_scope -> { order(action_at: :desc) }

  def action_at_be_in_the_future
    if action_at.present? && action_at > Date.today
      errors.add(:action_at, "未来の日付は登録できません。")
    end
  end

  def start_time
    action_at
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :histories, dependent: :destroy
  accepts_nested_attributes_for :histories
  mount_uploader :icon, ImageUploader
  validates :content, presence: true, length: { maximum: 20 }, uniqueness: { scope: :user_id, massage: "同じタスク名は登録できません" }
  validates :memo, length: { maximum: 400 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks, dependent: :destroy
  has_many :tasks_histories, through: :tasks, source: :histories
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :authenticate_user!

  def create
    @history = History.create(history_params)
    if @history.save
      flash[:success] = '実行日を追加しました'
      redirect_back(fallback_location: tasks_path)
    else
      flash[:danger] = '実行日追加に失敗しました'
      redirect_back(fallback_location: tasks_path)
    end
  end

  def destroy
    @history = History.find(params[:id])
    if @history.task.user_id == current_user.id
      @history.destroy
      flash[:success] = '記録を削除しました'
      redirect_to task_path(@history.task_id)
    else
      flash[:danger] = '記録を削除できませんでした'
      redirect_to task_path(@history.task_id)
    end
  end

  def calendar
    user = current_user
    @histories = user.tasks_histories
  end

  private

  def history_params
    params.require(:history).permit(:id, :task_id, :action_at)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      redirect_to tasks_path
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  require 'csv'

  before_action :authenticate_user!

  def index
    @tasks = current_user.tasks.includes(:histories)
    @task = Task.new
    @task.histories.build
    @history = History.new

    respond_to do |format|
      format.html
      format.csv do |csv|
        send_tasks_csv(@tasks)
      end
    end
  end

  def show
    @task = current_user.tasks.find(params[:id])
    @histories = @task.histories.order(action_at: :desc)
    @history = History.new
  end

  def create
    @task = current_user.tasks.create(task_params)
    if @task.save
      flash[:success] = 'タスクを追加しました'
      redirect_to tasks_path
    else
      flash[:danger] = 'タスク追加に失敗しました'
      redirect_to tasks_path
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:success] = 'タスクを編集しました'
      redirect_back(fallback_location: tasks_path)
    else
      flash[:danger] = 'タスク編集に失敗しました'
      redirect_back(fallback_location: tasks_path)
    end
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.user_id == current_user.id
      @task.destroy
      flash[:success] = 'タスクを削除しました'
      redirect_to tasks_path
    else
      flash[:danger] = 'タスクを削除できませんでした'
      redirect_to tasks_path
    end
  end

  def send_tasks_csv(tasks)
    csv_data = CSV.generate do |csv|
      header = %w(content user_id task_id memo action_at)
      csv << header

      tasks.each do |task|
        task.histories.each do |history|
          values = [history.task.content, history.task.user_id, history.task_id, history.task.memo, history.action_at]
          csv << values
        end
      end
    end
    send_data(csv_data, filename: "timefiles_tasks.csv")
  end

  private

  def task_params
    params.require(:task).permit(:content, :icon, :memo, histories_attributes: [:id, :action_at])
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create

  def check_guest
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの変更・削除はできません。'
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i(update destroy)

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの変更・削除はできません。'
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/views/histories/calendar.html.erb
<%= month_calendar events: @histories do |date, histories| %>
  <%= date.day %>
  <% histories.each do |history| %>
    <p><%= history.task.content %></p>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timefiles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div id="container">
      <%= render 'shared/flash' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="container-fluid">
  <small><a href="/"  style="color: #4d5156;">Copyright　© 2020  TimeFiles.</a></small>
</footer>

app/views/shared/_header.html.erb
  <section class="fixed-top bg-dark">
    <nav class="navbar navbar-expand-lg navbar-dark">
      <% if user_signed_in? %>
        <%= link_to "TimeFiles", tasks_path, class: "navbar-brand" %>
      <% else %>
        <%= link_to "TimeFiles", root_path, class: "navbar-brand" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <i class="fa fa-list-alt fa-fw fa-lg mr-1"></i><%= link_to "タスク一覧", tasks_path %>
            </li>
            <li class="nav-item">
              <i class="fa fa-calendar fa-fw fa-lg mr-1"></i><%= link_to 'カレンダー', calendar_path %>
            </li>
              <li class="nav-item">
              <i class="fa fa-user fa-fw fa-lg"></i> <%= link_to 'アカウント', edit_user_registration_path %>
            </li>
            <li class="nav-item">
              <i class="fa fa-sign-out fa-fw fa-lg mr-1"></i><%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <i class="fa fa-sign-in fa-fw fa-lg mr-1"></i><%= link_to "ログイン", new_user_session_path %>
            </li>
            <li class="nav-item">
              <i class="fa fa-user-plus fa-fw fa-lg mr-1"></i><%= link_to "新規登録", new_user_registration_path %>
            </li>
            <li>
              <i class="fa fa-hand-o-right fa-fw fa-lg mr-1"></i><%= link_to "ゲストログイン", users_guest_sign_in_path , method: :post %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </section>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading text-center">
    <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view, class:"back-next text-info" %>
    <span class="calendar-title"> <%= start_date.year %>年　<%= t('date.month_names')[start_date.month] %></span>
    <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view, class:"back-next text-info"  %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/static_pages/home.html.erb
<div class="container">
  <div id="carouselExampleSlidesOnly" class="carousel slide carousel-fade mb-4" data-ride="carousel"　data-interval="100">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="/images/TimefilesHP_1.png" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/images/TimefilesHP_2.png" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/images/TimefilesHP_3.png" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/images/TimefilesHP_4.png" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/images/TimefilesHP_5.png" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/images/TimefilesHP_6.png" alt="Second slide">
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row userlink mt-4">
    <div class="col-lg-6">
      <h3 class="text-center mt-5 mb-3">"あれ、いつやったっけ？"</h3>
      <h3 class="text-center m-3">"何日経ったかな？"</h3>
      <h3 class="text-center mt-4 mb-5">あなたの代わりに覚えます</h3>
    </div>
    <div class="col-lg-6">
      <h3 class="text-center mb-5"><strong>無料で会員登録</strong></h3>
      <div class="mx-auto mt-2" style="width: 300px; display: flex;">
        <p class="mx-auto"><%= link_to "新規登録", new_user_registration_path, class: "btn btn-info btn-lg" %></p>
        <p class="mx-auto"><%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-info btn-lg" %></p>
      </div>
      <div class="mx-auto mt-4 px-3" style="width: 300px;">
        <p class="text-center">
          <%= link_to "ゲストログイン", users_guest_sign_in_path , method: :post, class: "btn btn-outline-secondary btn-block" %>
        </p>
      </div>
    </div>
  </div>
  <div class="row explain mt-5 justify-content-around">
    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="/images/index.jpg">
      <div class="card-body">
        <p class="card-text"><strong>タスクと何日経ったかを一覧で　かんたんに確認できます</strong></p>
      </div>
    </div>
    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="/images/today.png">
      <div class="card-body">
        <p class="card-text"><strong>TODAYボタンを使って1クリックで経過日をリセットできます</strong></p>
      </div>
    </div>
    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="/images/calendar.jpg">
      <div class="card-body">
        <p class="card-text"><strong>カレンダーページで今月の履歴をすべて確認できます</strong></p>
      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="createtask">
  <button type="button" class="btn btn-outline-dark btn-block hidebtn" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    新規タスク
  </button>
  <div class="collapse" id="collapseExample">
    <div class="card" style="margin-top: -1rem;">
      <div class="card-body show-info" style="display: block;">
        <%= form_with(model: @task, local: true) do |f| %>
          <div class="form-group row">
            <label class="col-sm-2 col-form-label text-muted" for="">タスク追加</label>
            <div class="col-sm-9">
              <%= f.text_field :content, class:'form-control', onKeyUp:"countLength(value, 'textlength');" %>
              <P class="pull-right" id="textlength">0/20文字</P>
            </div>
          </div>

          <div class="form-group row">
            <%= f.fields_for :histories do |history| %>
              <label class="col-sm-2 col-form-label text-muted" for="">最終実行日</label>
              <div class="col-sm-9">
                <%= history.text_field :action_at, id: "flatpickr", class: 'form-control bg-white', type: "text" %>
              </div>
            <% end %>
          ​</div>
          <div class="text-right">
            <%= f.submit '新規作成', class: 'btn btn-outline-dark' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%#======================================%>
<div class="task_index">
  <% @tasks.each do |task| %>
    <% @histories = task.histories.order(action_at: :desc).first %>
    <div class="card">
      <div class="card-body">
        <p style="width: 50px;"><%= image_tag task.icon.thumb.url %></p>
        <div class="row index-namedate">
          <h4 class="task-title col-md-5"><%= link_to task.content, task, style: "color: #555555;" %></h4>
          <div class="col-md-6">
            <% if @histories.present? %>
              <h5><%= (Date.today - @histories.action_at).to_i %> DAYS AGO</h5> 
            <% else %>
              <h5 class="text-warning">NO DATE</h5>
            <% end %>
          </div>
        </div>
        <div class="task_menu">
          <%= form_with(model:[task, @history]) do |f| %>
            <%= f.hidden_field :task_id, :value => task.id %>
            <%= f.hidden_field :action_at, :value => Date.today %>
            <%= f.submit 'TODAY', class: 'btn btn-outline-dark mb-1' %>
          <% end %>
          <button type="button" class="btn btn-dark" style="width:78.78px"><%= link_to 'show', task %></button>
        </div>
        <div class="my-auto ml-1">
          <%= link_to task, method: :delete, data: 
            { confirm: 'タスクを削除しますか?',
              cancel: 'やめる',
              commit: '削除する'}, title: '削除確認', class: 'deletebtn' do %>
            <i class="fa fa-lg fa-remove fa-fw" style="color:firebrick"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="csv-button row justify-content-end">
  <%= link_to "<< CSV EXPORT >>", tasks_path(format: :csv), class: 'mr-4', style: "color: #555555;" %>
</div>

app/views/tasks/show.html.erb
<div class="card">
  <div class="card-body show-page" style="display: block;">
    <%= form_for(@task) do |f| %>
      <div class="show-taskinfo">
        <div class="container">
          <div class="row">
            <div class="show-icon col-lg-3">
              <p><%= image_tag @task.icon.url %></p>
              <div class="custom-file">
                <%= f.file_field :icon, class: 'custom-file-input', id: 'customFile', accept: "image/png,image/jpeg,image/gif" %>
                <label class="custom-file-label" for="customFile" data-browse="FILE">アイコン追加</label>
              </div>
            </div>
            <div class="taskname-date col-lg-8 col-md-7">
              <h4><i class="fa fa-edit fa-fw"></i><%= f.text_field :content, class: 'border-bottom', onKeyUp:"countLength(value, 'textlength');", style: 'border: none; color: #555555;" ' %></h4>
              <p class="task-rename">タスクの名前を変更できます<span class="pull-right" id="textlength"> 0/20文字</span></p>
              <div class="elapsed-date">
                <h4><i class="fa fa-calendar-minus-o fa-fw"></i>
                  <% if @histories.present? %>
                    <%= (Date.today - @histories.first.action_at).to_i %> DAYS AGO
                  <% else %>
                    NO DATE
                  <% end %>
                </h4>
              </div>
            </div>
          </div>
        </div>
        <%= f.text_area :memo, class: 'form-control', placeholder: 'memo' %>
        <div class="showbtninfo">
          <%= f.submit 'タスク更新', class: 'btn btn-outline-dark'%>
          <button type="button" class="btn btn-outline-danger">
            <%= link_to 'タスク削除', @task, class: 'text-danger', method: :delete, data: 
              { confirm: 'タスクを削除しますか?',
                cancel: 'やめる',
                commit: '削除する'}, title: '削除確認' %>
          </button>
        </div>
      </div>
    <% end %>
    <%#======================================%>
    <%= form_with(model:[@task, @history], local: true) do |history| %>
      <%= history.hidden_field :task_id, :value => @task.id %>
      <div class="addhistories">
        <%= history.text_field :action_at, id: "flatpickr", class: 'form-control bg-white', type: "text", placeholder: '実行日追加', readonly:""%>
        <%= history.submit '追加', class: 'btn btn-outline-dark addhistorybtn' %>
      </div>
    <% end %>
    <%#======================================%>
    <ul class="histories-preview">
      <% @histories.each do |history| %>
        <li class="list-group-item">
          <%= history.action_at.strftime("%Y年 %m月 %d日") %>
            <%= link_to task_history_path(@task, history), method: :delete, data: 
              { confirm: '記録を削除しますか?',
                cancel: 'やめる',
                commit: '削除する'}, title: '削除確認', class: 'historydeletebtn' do %>
              <i class="fa fa-lg fa-calendar-times-o" style="color:firebrick;"></i>
            <% end %>
        </li>
      <% end %>
    </ul>

    <div class="undermenu">
      <button type="button" class="btn btn-dark btn-sm"><%= link_to 'PAGE BACK', tasks_path %></button>
    </div>
  </div>
</div>